spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demos
    username: dchuang
    password: # (leave empty or insert password if needed)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # let Liquibase handle schema changes

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
